# Configuration for repository: github-config
name: github-config
description: "IaC configuration for managing GitHub organization repositories."
visibility: public
is_template: false
auto_init: true
gitignore_template: "Terraform"
license_template: "mit"
topics:
  - opentofu
  - github
  - iac
  - devops
archived: false
import_id: true
branch_protection:
  pattern: main
  enforce_admins: false
  require_signed_commits: true
  required_status_checks:
    strict: true
    contexts:
      - "CI / tofu-validate"
  required_pull_request_reviews:
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    required_approving_review_count: 1
