# Configuration for repository: github-config
name: github-config
description: "IaC configuration for managing GitHub organization repositories."
visibility: public
is_template: false
auto_init: true
gitignore_template: "Terraform"
license_template: "mit"
topics:
  - opentofu
  - github
  - iac
  - devops
import_id: true
branch_protection: null
